# Generated by Django 5.1.4 on 2024-12-18 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='questionoption',
            name='unique_correct_option',
        ),
    ]
