# Generated by Django 5.1.4 on 2024-12-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_questionoption_unique_correct_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='score',
            field=models.FloatField(default=0.0, verbose_name='Score (Percentage)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('done', 'Done')], default='active', max_length=20),
        ),
    ]
